"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Plugin management, managed by Vim-plug
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

set nocompatible
filetype off

call plug#begin('~/.vim/plugged')

" Theme
Plug 'liuchengxu/space-vim-dark'
" Languages
Plug 'vim-syntastic/syntastic'
Plug 'vhda/verilog_systemverilog.vim'
Plug 'tell-k/vim-autopep8'
Plug 'derekwyatt/vim-scala'
Plug 'tpope/vim-sensible'
Plug 'tomlion/vim-solidity'
Plug 'keith/swift.vim'
Plug 'posva/vim-vue'
Plug 'plasticboy/vim-markdown'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'Chiel92/vim-autoformat'
" Setup
Plug 'junegunn/fzf.vim'
Plug 'vim-scripts/AnsiEsc.vim'
Plug 'hecal3/vim-leader-guide'
Plug 'junegunn/goyo.vim'
Plug 'godlygeek/tabular'
Plug 'craigemery/vim-autotag'
Plug 'scrooloose/nerdtree'
Plug 'ryanoasis/vim-devicons'
Plug 'mhinz/vim-startify'
Plug 'sharkdp/bat'
Plug 'junegunn/rainbow_parentheses.vim'

call plug#end()

filetype plugin indent on

" Source scripts handling the rest of the settings
source ~/.vim/plugin/settings.vim
source ~/.vim/plugin/functions.vim
source ~/.vim/plugin/plugins.vim
source ~/.vim/plugin/snippets.vim
source ~/.vim/plugin/files.vim

" Open templates when editing a new file.
" Setup here else the template loaded is written twice
" in the new file (previously was in files.vim).
au bufNewFile *.cpp 0r      ~/.vim/templates/template.cpp
au bufNewFile *.h 0r        ~/.vim/templates/template.h
au bufNewFile *.v 0r        ~/.vim/templates/template.v
au bufNewFile *.html 0r     ~/.vim/templates/template.html
au bufNewFile *.py 0r       ~/.vim/templates/template.py
au bufNewFile *.scala 0r    ~/.vim/templates/template.scala

